---
title: "Discussion"
author: "Anela Layugan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Discussion}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Goals

###Goal 1: Hits and Misses
The low number of workers that missed truth fields can be explained by a somewhat faulty methodology and the psychology behind this project. The methodology used assumes that workers clearly saw truth fields in their grids and attempted to map them. Additionally, any worker fields in grids with truth fields were chosen as hits despite knowing whether they correspond to a truth field attempt or a different field attempt. Every worker might also assume that there are fields in every grid they are given, so they map anything they see even if it is not the truth field they contained in the grid.


### Goal 2: Summary Statistics
Workers may have mapped smaller fields than truth fields because the fields were outside of their grids, or sectionalized truth fields exist in which their sections are mistaken for smaller fields. The larger standard deviation of worker fields is explained by the large spread of human minds working on this project; workers may have different ideas of which fields exist in the same grid.


### Goal 3: Accuracy
As an example, worker field number 103 had a high true positive rate and low false positive rate, but the field was much smaller than the truth field resulting in a high false negative rate. Every worker field has these rates for accuracy assessment.


## Difficulties and Uncertainties
I had the most difficulty keeping track of the variables contained in each dataset; indexing into datasets using results from different functions confused the process quite a bit and I received many errors. In addition, writing the iterative codes seemed like a simple task when outlined, but I strayed from the original plan when it became too confusing. I stepped back to gain a better sense of the task at hand and created a code that was more intuitive to my understanding of the project.


## Next Steps
I understood that the most important goal for this project was calculating the accuracy rates for each worker field, so obtaining those results consumed most of the time I had for this project. If I had more time, I would take the methodolody used for Goal 3 and apply it to Goals 1 and 2 for better accuracy. I would also simplify and condense my codes for Goal 3 for better elegance. Finally, I did not have time to calculate the statistics of the accuracy of each individual worker. I hope to be given the chance to complete these aspects of the project after submitting this report.

Despite any drawbacks and future code edits, the current results of this project will be given to Mapping Africa for further analysis. The truth fields that workers missed will be analyzed for commonalities, such as field type and active/past field status that were not available for this aspect of the project. The accuracy rates of each worker field and the summary statistics of those rates for each worker provides insight into how well the human eye can detect fields using satellite imagery. Perhaps workers with higher accuracy will be asked to map fields in the future.
